prometheus-blackbox-exporter:
  fullnameOverride: prometheus-blackbox-exporter

  restartPolicy: Always

  kind: Deployment

  ## Enable pod security policy
  pspEnabled: true

  hostNetwork: false

  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate

  ## User to run blackbox-exporter container as
  runAsUser: 1000
  readOnlyRootFilesystem: true
  runAsNonRoot: true

  livenessProbe:
    httpGet:
      path: /health
      port: http

  readinessProbe:
    httpGet:
      path: /health
      port: http

  config:
    modules:
      http_2xx:
        prober: http
        timeout: 5s
        http:
          headers:
              User-Agent: "blackbox-monitoring"
          valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
          no_follow_redirects: false
          preferred_ip_protocol: "ip4"
      icmp_ipv4:
        prober: icmp
        icmp:
          preferred_ip_protocol: ip4

  allowIcmp: true

  resources:
    limits:
      memory: 300Mi
    requests:
      memory: 50Mi

  service:
    type: ClusterIP
    port: 9115

  containerPort: 9115

  serviceAccount:
    create: true

  pod:
    labels: {}

  extraArgs: []
  #  --history.limit=1000

  replicas: 1
